ublox_gps_node:
  ros__parameters:
    device: /dev/gps
    frame_id: gps
    #uart1:
    #  baudrate: 38400
    #  in: 32                    # RTCM 3
    #  out: 0                    # No UART out for rover
    
    gnss:
      glonass: true             # Supported by C94-M8P
      beidou: true             # Supported by C94-M8P
      galileo: true
      qzss: false               # Supported by C94-M8P
    
    config_on_startup: true
    
    # TMODE3 Config
    tmode3: 0                   # Survey-In Mode
    sv_in:
      reset: false              # True: disables and re-enables survey-in (resets)
                                # False: Disables survey-in only if TMODE3 is
                                # disabled
      min_dur: 10              # Survey-In Minimum Duration [s]
      acc_lim: 30.0              # Survey-In Accuracy Limit [m]
    
    inf:
      all: false                 # Whether to display all INF messages in console

    rate: 5.0                   # in Hz
    nav_rate: 1                 # [# of measurement cycles], recommended 1 Hz, be
                                # may either 5 Hz (Dual constellation) or
                                # 8 Hz (GPS only)
    dynamic_model: pedestrian     # Airborne < 2G, 2D fix not supported (3D only),
                                # Max Alt: 50km
                                # Max Horizontal Velocity: 250 m/s,
                                # Max Vertical Velocity: 100 m/s
    fix_mode: auto
    enable_ppp: false           # Not supported by C94-M8P
    dr_limit: 0
    dgnss_mode: 2               # 2 RTK float (prevents jumps), 3 RTK Fixed mode
    
    
    # Enable u-blox message publishers
    publish:
      all: false
      aid:
        hui: false

      nav:
        posecef: false
